app:
  env:
    label: PANNET
    color: yellow

apiVersion: 1.0.0
logging:
    level:
        com:
            assignment:
                springboot:
                    mongo: DEBUG
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
server:
    port: 9007
spring:
    data:
        mongodb:
            database: BMP_UDMMANAGEMENT_1
            host: 172.29.1.114
            port: 27017
udmManagementURL: http://172.31.8.16:8080/bss/v1/

